// AstraeaGoddess — Lady Justice / 星之女神, rendered as mono symbol art.
// AUTO-GENERATED by scripts/gen-goddess.sh from assets/goddess-source.png
//   (PIL crop 0.30w,0.02h..0.71w,h → chafa --format symbols -c none --size 38x30).
// Mono grey-white on the terminal's dark bg; a silver shine band sweeps top→bottom
// during the boot reveal (AstraeaIntro). Do not hand-edit — re-run the script.

import React from 'react'
import { Box, Text } from 'ink'

const GREY = '#C0C8D6'   // resting grey-white (faithful to the source art)
const SHINE = '#E8F0FF'  // silver shine highlight (boot reveal band)

export const GODDESS_LINES: string[] = [
  " ▁      ╴      ▂▏╼━┅╌▂╴               ",
  "       ╵     ▂▇╼▂▟▄▊▂╊▐▖     ┬ ┄      ",
  "     ╶      ▕▉▎╺██▙█▉┑▕▉▄             ",
  "         ┄╌╴┼▉▎▆▙███▞▇▍▉╂ ┄─╴     ╵   ",
  "            ▕▉▎█┏███▚▟▗▉▎     ▅▇▖     ",
  " ╸          ▕▔▝█▆▐█▉▝▔▝▘     ▟▛┚▘     ",
  "             ▃▆█▛████▜▜▙▂▁  ▇▛▀┲▀━╾   ",
  "            ▕█▐▐▗███▇█┐▜██▆▛▔▘    ▔╴  ",
  "       ╶╴╷  █▉╿▘██████▍ ▔▝▀▝ ╲   ╱    ",
  "            █▉▝█▁▁▀▛▁▏╷▏▐ ┕▆▆━   ━▆▆╸ ",
  "           ▟█▌▕╴█╹▀▝╹▏╵ ▐▖           ╌",
  "          ▕█▛ ▟███▉▏▁▐▍ ▎▜▎      ▁  ▕ ",
  "  ▔    ▁ ▜▟▊│┳▇█▛█▙▕█▐█▌▕▝█▖      ╎   ",
  "          ▜▜▃┵▔▃▀▔▛▟█▎┏▜  ▝█▖         ",
  "         ▂┲▀▇▖╋▜╳▊▚██╸▂ ┨╌┇▝█▅        ",
  "▔▔▔▔▔▔▔▔▟█▍ ╷▜▆▐▇▘▃▇▁▟▇▖ ┈▎▗▔█▇▖▔▔▔▔▔▔",
  " ┇│ ▏  ▟██ ▏▕▁▜▙▘▕╴▗███▌╷╍▎┕▘▕▜█▙▏│   ",
  "  │ ▏ ▁▇▇▎╶▏┄▁▄▝▙▖ ▐██▍╴╎ ┄╷▏┰╴┖▇▖│   ",
  " ┋│ ▏ ╲┷▊▎┊▗▕╏┫ ▞█▖▕▀█▊▗▎▁▔│▏  ╿╾▔│   ",
  " ┋│ ▏   ╶▏ ▛┝▂┭▘▁▕▜▅▝▛█▖█▜▖    └ ▏│   ",
  "  ╵╵╻   ▔ ▃▘╹▘│╱█▎▏▀▙▏▀▌▝▍▜▎     ╹╵▔╷ ",
  "  ╎      ▂▍╉▕▊▟▍█▍▉╇▞█▕█▋▝▂▜▅     ╎   ",
  "▕     ▔▗▟▀▟▘▇▘█▐█▊▀▙█▄▘╴█▖▀▙▝▜▄▅┒   ▔ ",
  "╶┈┄ ┄ ╴▔▘▝▔╋▊▀████▉█▝██▌▝▉┳▝▀╼▝▀▀▘╷ ┄ ",
  "       ╷    ╷▔▔ ▔▔ ▔▔▔▀ ▕▔▏  ╷        ",
]

export const GODDESS_HEIGHT = GODDESS_LINES.length
export const GODDESS_WIDTH = 38

/** During the boot reveal: how many lines are shown, and which one is the
 *  bright silver leading edge. Omit entirely for the settled resting art. */
export interface GoddessReveal { shown: number; band: number }

/**
 * Renders the goddess as a fixed GODDESS_WIDTH×GODDESS_HEIGHT block.
 *   reveal === undefined           → all lines settled grey-white
 *   i >= reveal.shown              → blank placeholder (height preserved)
 *   i === reveal.band              → silver shine (bold)
 *   else                           → settled grey-white
 * The block is left-aligned internally so columns stay aligned; the PARENT
 * centers it as one unit (never center the rows individually).
 */
export function AstraeaGoddess({ reveal }: { reveal?: GoddessReveal }): React.ReactNode {
  return (
    <Box flexDirection="column">
      {GODDESS_LINES.map((line, i) => {
        if (reveal && i >= reveal.shown) return <Text key={i}>{' '}</Text>
        const color = reveal && i === reveal.band ? SHINE : GREY
        const bold = reveal ? i === reveal.band : false
        return <Text key={i} color={color} bold={bold}>{line}</Text>
      })}
    </Box>
  )
}
