// AstraeaWordmark — 'Astraea' rendered in the ANSI Shadow figlet font.
// AUTO-GENERATED by scripts/gen-wordmark.ts. Base color = brand indigo; an optional
// silver shine band sweeps across columns (used by the boot intro AstraeaIntro).

import React from 'react'
import { Box, Text } from 'ink'
import { INDIGO, SILVER } from './theme'

// Block-art lines (all glyphs are BMP → String.length === visible columns).
export const WORDMARK_LINES: string[] = [
  " █████╗ ███████╗████████╗██████╗  █████╗ ███████╗ █████╗ ",
  "██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██╔══██╗",
  "███████║███████╗   ██║   ██████╔╝███████║█████╗  ███████║",
  "██╔══██║╚════██║   ██║   ██╔══██╗██╔══██║██╔══╝  ██╔══██║",
  "██║  ██║███████║   ██║   ██║  ██║██║  ██║███████╗██║  ██║",
  "╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝",
]

export const WORDMARK_WIDTH = Math.max(...WORDMARK_LINES.map(l => l.length))
export const WORDMARK_HEIGHT = WORDMARK_LINES.length

// Half-width of the silver shine band (band spans 2*SHINE_HALF columns).
const SHINE_HALF = 4

/** True when the terminal is wide enough to show the full block wordmark. */
export function fitsWordmark(columns: number): boolean {
  return columns >= WORDMARK_WIDTH
}

/**
 * Renders the wordmark.
 *   shineCenter === undefined → solid indigo (settled / resting state)
 *   shineCenter === <col>     → silver band centered at that column (animation frame)
 */
export function AstraeaWordmark({ shineCenter }: { shineCenter?: number }): React.ReactNode {
  const a = shineCenter === undefined ? null : Math.round(shineCenter - SHINE_HALF)
  const b = shineCenter === undefined ? null : Math.round(shineCenter + SHINE_HALF)

  return (
    <Box flexDirection="column">
      {WORDMARK_LINES.map((line, i) => {
        if (a === null || b === null || b <= 0 || a >= line.length) {
          // No band on this line → solid indigo.
          return <Text key={i} color={INDIGO}>{line}</Text>
        }
        const lo = Math.max(0, a)
        const hi = Math.min(line.length, b)
        return (
          <Text key={i}>
            <Text color={INDIGO}>{line.slice(0, lo)}</Text>
            <Text color={SILVER} bold>{line.slice(lo, hi)}</Text>
            <Text color={INDIGO}>{line.slice(hi)}</Text>
          </Text>
        )
      })}
    </Box>
  )
}
