#!/usr/bin/env bash
# gen-goddess.sh — regenerate src/ui/AstraeaGoddess.tsx from assets/goddess-source.png
#
# One-shot static asset (like the AUTO-GENERATED AstraeaWordmark). The welcome
# screen ships the baked GODDESS_LINES constant — chafa/PIL are NOT runtime deps.
#
# Pipeline:
#   1) PIL crops the source to the central figure (box = 0.30w,0.02h .. 0.71w,h)
#   2) chafa renders mono symbol art at 38 cols (aspect → 25 rows)
#   3) each row is right-padded to exactly 38 columns and emitted as a TS array
#
# Requires: python3 + Pillow, chafa (brew install chafa).
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=assets/goddess-source.png
CROP=$(mktemp -t goddess_crop).png
OUT=src/ui/AstraeaGoddess.tsx
WIDTH=38

python3 - "$SRC" "$CROP" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert('RGB')
w, h = im.size
box = (int(w*0.30), int(h*0.02), int(w*0.71), h)
im.crop(box).save(sys.argv[2])
PY

chafa --format symbols -c none --size ${WIDTH}x30 "$CROP" > "$CROP.txt"

python3 - "$CROP.txt" "$WIDTH" "$OUT" <<'PY'
import sys, json
lines_path, width, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
raw = open(lines_path, encoding='utf-8').read().split('\n')
# drop trailing empty line(s) from the final newline
while raw and raw[-1].strip() == '':
    raw.pop()
# normalize every row to exactly `width` columns (all glyphs are width-1 BMP)
rows = [ (r[:width]).ljust(width) for r in raw ]
arr = ',\n'.join('  ' + json.dumps(r, ensure_ascii=False) for r in rows)
banner = (
    "// AstraeaGoddess — Lady Justice / 星之女神, rendered as mono symbol art.\n"
    "// AUTO-GENERATED by scripts/gen-goddess.sh from assets/goddess-source.png\n"
    "//   (PIL crop 0.30w,0.02h..0.71w,h → chafa --format symbols -c none --size 38x30).\n"
    "// Mono grey-white on the terminal's dark bg; a silver shine band sweeps top→bottom\n"
    "// during the boot reveal (AstraeaIntro). Do not hand-edit — re-run the script.\n\n"
)
body = (
    "import React from 'react'\n"
    "import { Box, Text } from 'ink'\n\n"
    "const GREY = '#C0C8D6'   // resting grey-white (faithful to the source art)\n"
    "const SHINE = '#E8F0FF'  // silver shine highlight (boot reveal band)\n\n"
    f"export const GODDESS_LINES: string[] = [\n{arr},\n]\n\n"
    "export const GODDESS_HEIGHT = GODDESS_LINES.length\n"
    f"export const GODDESS_WIDTH = {width}\n\n"
    "/** During the boot reveal: how many lines are shown, and which one is the\n"
    " *  bright silver leading edge. Omit entirely for the settled resting art. */\n"
    "export interface GoddessReveal { shown: number; band: number }\n\n"
    "/**\n"
    " * Renders the goddess as a fixed GODDESS_WIDTH×GODDESS_HEIGHT block.\n"
    " *   reveal === undefined           → all lines settled grey-white\n"
    " *   i >= reveal.shown              → blank placeholder (height preserved)\n"
    " *   i === reveal.band              → silver shine (bold)\n"
    " *   else                           → settled grey-white\n"
    " * The block is left-aligned internally so columns stay aligned; the PARENT\n"
    " * centers it as one unit (never center the rows individually).\n"
    " */\n"
    "export function AstraeaGoddess({ reveal }: { reveal?: GoddessReveal }): React.ReactNode {\n"
    "  return (\n"
    "    <Box flexDirection=\"column\">\n"
    "      {GODDESS_LINES.map((line, i) => {\n"
    "        if (reveal && i >= reveal.shown) return <Text key={i}>{' '}</Text>\n"
    "        const color = reveal && i === reveal.band ? SHINE : GREY\n"
    "        const bold = reveal ? i === reveal.band : false\n"
    "        return <Text key={i} color={color} bold={bold}>{line}</Text>\n"
    "      })}\n"
    "    </Box>\n"
    "  )\n"
    "}\n"
)
open(out, 'w', encoding='utf-8').write(banner + body)
print(f"wrote {out}: {len(rows)} lines × {width} cols")
PY

rm -f "$CROP" "$CROP.txt"
